name: quick_interact
description: A flutter package for showing quick interactions for any widget
version: 1.0.1
homepage: https://github.com/onatcipli/quick_interact.git

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_vibrate: ^1.3.0

dev_dependencies:
  flutter_lints: ^2.0.3
  flutter_test:
    sdk: flutter

flutter:

